### ISSUE TITLE
'required' initializer must be accessible wherever class 'NetworkWorker' can be subclassed

### ISSUE THREAD

**Issue by georgeathanasopoulositt** [scribd/Weaver#129]
First of all I'd like to sincerely thank you for taking such an initiative and starting Weaver for Swift.
It has a lot of pros - like building an AST and validating it at compile time - and or sure such a DI library was missing from the Swift Community.

Nevertheless, I find myself a bit confused, and I'm not sure whether I'm misusing Weaver incorrectly or this is a bug.

Here's what I'm trying to do:
1) I'm building from scratch our Corporate iOS app, using Swift
2) I'm building from scrach our Corporate iOS Framework, using Swift, as a private CocoaPod, imported by 1 mentioned above
3) I'm importing weaver in 2 mentioned above using CocoaPods, so that some base classes of the Framework (and after that, the App itself) will make use of weaver DI Framework.
4) In the framework (2), I have created some classes which need to be declared open so that they can be subclassed by the app (1). Declaring these classes as public (and, obviously, private) won't let me subclass them in the project that I have imported them using CocoaPods, as a Framework.

Here's what I'm getting from the compiler:
1) 'required' initializer must be accessible wherever class 'ITTNetworkWorker' can be subclassed

2) Insert 'public '

3) Initializer must be declared internal because its parameter uses an internal type

which are contradictory:

- if I insert public, the DI Framework and the auto-generated code works, but when I import this code as a Framework to the app, the class cannot be subclassed.

- If I set it as "internal", I get the same result

How can I make it work with "open"?
Any ideas?

**Comment by trupin** [comment]
Hi @georgeathanasopoulositt,

Just to clarify, Weaver isn't designed to generate any exposed (public) boilerplate code besides a convenience initializer for root types (public types). This convenience initializer internally builds a dependency container instance by injecting public dependencies passed as parameters.

As an example, you can look at the [`MovieAPI`](https://github.com/scribd/Weaver/blob/master/Sample/API/Manager/API.swift) type from Weaver's sample application. Not that this type is public, thus can be built from outside the `API` framework. Which is why Weaver generates a public [convenience initializer](https://github.com/scribd/Weaver/blob/d3909d483aab16d6a03705ebf2b90954b951f508/Sample/API/Generated/Weaver.swift#L219-L225) which abstracts the dependency container.

As for declaring an open class in a framework. I gave it a try by making `MovieAPI` open. I was able to subclass it like so:

```swift
final class MovieAPISubClass: MovieAPI {
    convenience init() {
        self.init(urlSession: .shared)
    }
}
```

I hope this helps understand how Weaver is meant to be used in libraries.

**Comment by trupin** [comment]
@georgeathanasopoulositt I'm closing this issue since it didn't get any activity in a while.

Feel free to reopen if you have further questions on the topic.
