### ISSUE TITLE
Property wrapper registration and reference with parameters

### ISSUE THREAD

**Issue by Mattot** [scribd/Weaver#131]
I tried to register my dependency MyCoordinatorProtocol in AppDelegate.
MyCoordinatorProtocol has one weaver defined parameter - AppCoordinatorProtocol.

Here is the registration code inside AppDelegate:
`@WeaverP1(.registration, type: MyCoordinator.self, scope: .weak)
    private var myCoordinator: (AppCoordinatorProtocol) -> MyCoordinatorProtocol`

Then I tried to define this dependency inside other class as follows:
`@WeaverP1(.reference)
    private var myCoordinator: (AppCoordinatorProtocol) -> MyCoordinatorProtocol`

And finally - I tried to use it:
`myCoordinator(appCoordinator).start()`
(`.start()` is function defined in MyCoordinatorProtocol)

What I got after hitting build:
Dependency 'myCoordinator' cannot declare parameters and be registered with a container scope.

Am I missing something?

**Comment by trupin** [comment]
Hello @Mattot,

Sorry for the late reply.

Weaver doesn't allow dependencies taking parameter(s) to be stored with a container scope. This is because a dependency taking parameter(s) and with a container scope needs these parameters requirements to be met at initialization of the container, which is possible, since these parameters are designed to be passed manually later on.
