### ISSUE TITLE
Missing project setup instructions for contributors

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#37]
I want to contribute to #31 but I am not able to run the `WeaverCodeGen` target.

Forked, cloned, and then ran `swift build` ✅

👉 Now I'm stuck at missing build input files.
![image](https://user-images.githubusercontent.com/5576161/41341167-5a0870a8-6ef9-11e8-9f08-c925a24c2c45.png)

Can you advise me on next steps?

I'm aware that I can run the tests with `swift test`, but I'd rather be able to build the target / run tests in Xcode.

**Comment by trupin** [comment]
Happy that you're willing to help on this project @ferologics!

Indeed, I haven't written anything for contributors so far. I'll do it in the context of this ticket.

For your issue, I suppose you're using Xcode 10 with swift 4.2. `WeaverCodeGen` doesn't compile so far because of `Yams`, which apparently doesn't support swift 4.2 either at this time. We should ask them when they think they could fix that, or open a PR on their project. Until then, you can install the build tools of Xcode 9.4 and switch to swift 4.1.2 with `xcode-select -s`. I tried yesterday to use Xcode 10 with the build tools of Xcode 9.4, and it works pretty, well. But if you don't want to do that, I'm afraid you'll have to use a lower version of Xcode; between 9.0 and 9.4.

Also, after switching between version of the build tools, you'll have to clean and reinstall with `make clean && make install`, and possibly regenerate the `xcodeproj` with `swift package generate-xcodeproj` (try to use this last command only if the first one doesn't work).

Good luck! 😃

**Comment by trupin** [comment]
@ferologics FYI, Weaver is now compatible with Swift 4.2 and Xcode 10.

**Comment by trupin** [comment]
Also, I stopped versioning the `xcodeproj` since it can be generated by Swift Package Manager. To start editing the project in Xcode, you'll now have to run `swift package generate-xcodeproj`

**Comment by ferologics** [comment]
Yeah, Swift package manager is totally out there, and this is an excellent use of another indispensable utility it offers.
