### ISSUE TITLE
How to test in Weaver integrated project?

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#38]
Any special instructions on how to use Weaver in my test target?

```
2018-06-13 21:58:12.427068+0200 xctest[41275:1125142] The bundle “Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-06-13 21:58:12.427544+0200 xctest[41275:1125142] Library not loaded: @rpath/WeaverDI.framework/WeaverDI
  Referenced from: Tests
  Reason: no suitable image found.  Did find:
	/Source/Carthage/Build/iOS/WeaverDI.framework/WeaverDI: required code signature missing for 'Source/Carthage/Build/iOS/WeaverDI.framework/WeaverDI'
)
```

How would I go about the signing part?
My small research bore no fruits 👉

Maybe [this](https://github.com/Carthage/Carthage/issues/1401)
Stackoverflow delete [derived data advice](https://stackoverflow.com/questions/40110392/required-code-signature-missing-for-a-library)
My [google query](http://bfy.tw/IaiY)

**Comment by trupin** [comment]
My first thought is that you're probably trying to build the tests for your iPhone, which requires a signed bundle.

This is what you should see in the top left corner of Xcode
<img width="153" alt="screen shot 2018-06-13 at 1 28 55 pm" src="https://user-images.githubusercontent.com/3514976/41376350-d585d7d4-6f0d-11e8-99ad-349d553b6b66.png">

The reason why it needs to run on maxOS is that this target runs the tests for `WeaverDI` and `WeaverCodeGen`, and `WeaverCodeGen` depends on `Sourcekitten`, which can't run on iOS.

Also, as I was saying in #37, if you recently switch Xcode version, you'll probably have to clean and reinstall with `make clean && make install`, and possibly regenerate the `xcodeproj` with `swift package generate-xcodeproj` if you're not using Xcode 9.4 (do that only if necessary since it will probably conflict with other developers environments).

**Comment by ferologics** [comment]
Actually, I'm running a personal project and the test target gives me the aforementioned error.

**Comment by ferologics** [comment]
The test target runs on simulator.

**Comment by trupin** [comment]
Oh my bad, I misunderstood your question. Thought you were trying to execute the tests of weaver.

**Comment by trupin** [comment]
There's nothing special to know, it should work as any imported framework in your tests. Let me setup a project with Carthage to see if I get into the same error.

**Comment by trupin** [comment]
I succeeded to run the test target on the sample without any problem with Carthage.

I had to add the following script build phase in the main target though, but I'm not sure it will help with your issue. It's worth a trying if you haven't done it already.

<img width="933" alt="screen shot 2018-06-13 at 4 17 08 pm" src="https://user-images.githubusercontent.com/3514976/41383396-6173b13c-6f25-11e8-994d-c405cdfff240.png">

**Comment by ferologics** [comment]
I don't have an app target, just a framework and it's test target.

**Comment by ferologics** [comment]
I had to set up test host application and add a build run script phase to recursively sign the embedded frameworks:

```
for f in $(find $CODESIGNING_FOLDER_PATH -name ‘*.framework’)
do
echo “$f”
codesign  --force --sign ${CODE_SIGN_IDENTITY} --preserve-metadata=identifier,entitlements --timestamp=none “$f”
done
```

**Comment by ferologics** [comment]
Thanks a ton @trupin! By comparing I was able to get it up and running without extra signing build step script phase 🍾

**Comment by trupin** [comment]
Happy to help! 😃

**Comment by ferologics** [comment]
On the side note - in the sample you provided - I think there is no need for the `carthage copy-frameworks` in the API target?

**Comment by trupin** [comment]
I think it depends on if you want to embed the dependencies or not. Not doing so will requires your framework users to embed it in their app themselves.

I'm no expert of embedding frameworks, so I could be wrong here. I'm curious about the answer if you have it though.
