### ISSUE TITLE
Generating only one output file

### ISSUE THREAD

**Issue by lyzkov** [scribd/Weaver#77]
Having multiple output files per container is a little bit tricky because each time I have to manually add generated file to the project. Is there any possible way to generate one file with a non-changing name that could be added to the XCode project only once?

**Comment by trupin** [comment]
Hi Lyskov,

Thanks for taking the time to file this. 

It sounds like a reasonable request. I’ll try something out and let you know what I get.

Théo

**Comment by trupin** [comment]
Hey @lyzkov,

I just merged a PR which adds the flag `--single_output` which generate the code into one unique file named `Weaver.swift`.

For example, the following writes the file `${SOURCE_ROOT}/Sample/Generated/Weaver.swift`
```bash
$ weaver generate --single_output --output_path ${SOURCE_ROOT}/Sample/Generated/ `find ${SOURCE_ROOT}/Sample -name '*.swift' | xargs -0`
```

Let me know if you have any other concerns with this issue, otherwise, I'll push a new release soon.

Théo.

**Comment by artrmz** [comment]
Btw. It should not import the same thing multiple times though ;)
