### ISSUE TITLE
Support generating xcfilelists

### ISSUE THREAD

**Issue by tonyarnold** [scribd/Weaver#84]
One of the new features in Xcode 10 is the ability to derive the input and output files for a build phase from `.xcfilelist` files.

My use case is that I would like to generate my output Weaver sources into the `DERIVED_SOURCES_DIR` - and that's fine, and possible using a custom build phase - however in order for Xcode to be able to do this efficiently, input and output files should be provided.

There's more information in [Xcode's release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10?language=objc) and there are a few [useful posts](http://www.gietal.net/blog/xcode10-and-prebuild-script-output-files-xcfilelist) around about it, too.

**Comment by trupin** [comment]
HI @tonyarnold,

This is an excellent idea. Generating the input & output lists should be pretty straightforward and is something which could easily be shipped with the next version of Weaver.

I think I can free some time soon to work on it, unless you want to give it a try. Just let me know what works the best for you.

By the way, I wonder if Xcode 10 is also optimizing the build phase by checking if any of the files in the input list changed. It'd be a nice optimization which we would get for free.

**Comment by trupin** [comment]
> honestly, I'd love to work on the feature, but I won't have time for about a month at this stage. If you get to it before me, I will not be upset

Indeed, I hope I'll have time to work on this before you do 😂

**Comment by trupin** [comment]
Hey @tonyarnold,

I have been working on the `xcfilelist` files generation a little bit and I feel like I came up with a good working solution (implemented in #86 so far).

The idea is to use the command `xcfilelist` to automatically generate the `xcfilelist` files.

For example:
```bash
$ weaver xcfilelist --output_path ${SOURCE_ROOT}/Sample/Generated/ `find ${SOURCE_ROOT}/Sample -name '*.swift' | xargs -0`
```

This way, each time a a developer adds annotations to a new type, the only thing to do is run that command so that Xcode is aware that the Weaver build phase needs to re-run. This is obviously a manual operation which can be forgotten and/or tedious, so I thought about adding a build phase for this.

One to generate the `xcfilelists` automatically.
<img width="1062" alt="screen shot 2019-01-30 at 10 35 00 pm" src="https://user-images.githubusercontent.com/3514976/52035383-4a0a3280-24df-11e9-9b3c-7c2a9264bc09.png">

One to generate the sources.
<img width="1379" alt="screen shot 2019-01-30 at 10 35 47 pm" src="https://user-images.githubusercontent.com/3514976/52035443-66a66a80-24df-11e9-8f71-cd1c17b387b9.png">

It turns out to work pretty well in the sample project.

What do you think?

Also, I realize that these commands could be a lot less tedious to type if Weaver was able to read a config file rather than taking all its parameters from the command line. That's another improvement which could make this feature look a lot better. I'll file it and implement it soon since it's something I have been wanting to do for quite a long time now.

**Comment by trupin** [comment]
After talking about this on a [SwiftGen ticket](https://github.com/SwiftGen/SwiftGen/issues/441#issuecomment-459237773) and according to the [WWDC video](https://developer.apple.com/videos/play/wwdc2018/408/?time=832) about this topic, generating `xcfilelist` files during the build process isn't something safe to do. 

> The important thing to note here, though, is that these [xcfilelist] files cannot be modified or generated throughout your build process. They are read when your build process starts. And all that information is used then.

Running the command manually is definitely going to be tedious without the option of reading its parameters from a configuration file. I'll make that happen for this feature.

**Comment by trupin** [comment]
Hi @tonyarnold,

I just merged #86 which adds an `xcfilelist` command to Weaver. Few things changed with how weaver now handles the `--input-path`. You can either use the `--input-path` variadic option with a glob expression (e.g. `--input-path "*.swift" --input-path "**/*.swift"` or write a configuration file which should be named `.weaver.yaml` or `.weaver.json` if you prefer JSON over YAML.

I'll improve the README soon to explain how to use the config file. Until then, you can take example on the [sample project](https://github.com/scribd/Weaver/blob/master/Sample/.sample.weaver.yaml).

Let me know if you have any questions/concerns.

**Comment by tonyarnold** [comment]
Fantastic @trupin, thanks! I'll let you know if I have any dramas using  this.

**Comment by trupin** [comment]
Closing as the #86 is now merged and released. @tonyarnold feel free to reopen if necessary.
